title: egpBos.nl
description: >- # this means to ignore newlines until "baseurl:"
  Evert Gerardus Patrick Bos' website - 
  incomplete, unoriginal, unsubstantiated, without necessary nuance -
  subpar standards, for subpar readers like me and you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://egpbos.nl" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: egpbos
# github_username:  egpbos
# linkedin_username: egpbos

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: classic
  social_links:
  - { platform: github,         user_url: "https://github.com/egpbos" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=3Le2IcUAAAAJ" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/egpbos" }
  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1199693/egpbos" }
  - { platform: x,              user_url: "https://x.com/egpbos" }
